### ISSUE TITLE
How to control corner roundness?

### ISSUE THREAD

**Issue by Sogatori** [DexterMagnific/QSvgStyle#6]
Hello,
I was wondering how I can control the amount of corner rounding in my theme. Like e.g. having the corners be fully rounded instead of just 4px. Is there something like frame.width that only affects the corners and not the edges?

**Comment by DexterMagnific** [comment]
Hi,

I'm not sure I understand your request. You mean getting something like Mac OS Aqua buttons ? (no left/right edges, fully rounded) ?

If so this is currently not possible. Rounding is only for corners, and there must be straight edges. This is useful because you cannot guarantee that your button has a fixed height. What would you do with this kind of roundness if you have a big button (with text on multiple lines) ?
